name: links

on: push

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: .mlc-config.json
